### ISSUE TITLE
Error with minify CSS

### ISSUE THREAD

**Issue by Ande1232** [dead23angel/smarty-combine#1]
Hello i have a problem, I installed the plugin, and it seems it works with JS, and me generate the files in cache. 
But if I try to create a CSS file gives me this error:

`Fatal error: Cannot redeclare class JSMin_UnterminatedStringException in C:\xampp\htdocs\beta\include\librerie\Smarty\plugins\minify\JSmin.php on line 435`

This is my code:

`{combine input=array('/beta/_inc/public/plugins/search.js','/beta/_inc/public/plugins/pagination.js','/beta/_inc/public/plugins/load/jquery_load.js') output='/beta/cache/big.js' age='30' debug=false}

{combine input=array('/beta/_inc/public/plugins/owl-carousel/owl.carousel.css','/beta/_inc/public/plugins/font-awesome/css/font-awesome.min.css') output='/beta/cache/big.css' age='30' debug=false}`

**Comment by dead23angel** [comment]
Hi, @Ande1232!
Your error occurs because you have already found in the code JSMin_UnterminatedStringException class.

The easiest way to deal with this mistake is to rename JSMin_UnterminatedStringException class in C:\xampp\htdocs\beta\include\librerie\Smarty\plugins\minify\JSmin.php file
Lines 161, 203, 435
Calling for example, you can JSMin_UnterminatedString2Exception

**Comment by Ande1232** [comment]
Hi @dead23angel,

I replaced everything as you suggested, unfortunately continues to give me error. The error I've only if I also want to compress css, if I remove the string for the CSS, It created the minify JS files without error.

`Fatal error: Cannot redeclare class JSMin_UnterminatedString2Exception in C:\xampp\htdocs\beta\include\librerie\Smarty\plugins\minify\JSmin.php on line 435`

**Comment by dead23angel** [comment]
Hi @Ande1232!
Tell me which version you are using Smatry, so I tried to reproduce the bug

**Comment by dead23angel** [comment]
@Ande1232 I made changes to avoid similar mistakes. Try to update the plugin.

**Comment by Ande1232** [comment]
@dead23angel It's working fine now thanks.

**Comment by sergeevizh** [comment]
Hello.
{combine input=array('/design/default/css/bootstrap.css','/design/default/css/tip.css') output='/cache/main.css' age='30' debug=false}

When using style compression, the site stops working. A file is created in the cache folder, but with 0 weight.

![Image of Yaktocat](http://forum.simplacms.ru/uploads/monthly_04_2017/post-18154-0-72777200-1492870687.png)
