### ISSUE TITLE
Add remote files

### ISSUE THREAD

**Issue by masimao** [dead23angel/smarty-combine#3]
This is a awesome plugin! My congrats!

I my case i have to load some remote files, do you plan to implement this feature?

Other question, will you keepe active this project?

**Comment by dead23angel** [comment]
@masimao hi!
I did not plan to do support for remote files. I'm engaged in the project in my spare time, since I basically switched to another template engine, I use Blade

**Comment by masimao** [comment]
Hi @dead23angel,

I am using Smarty with a micro framework we've done. I need to minify a lot of JS/CSS included in each page, so i am looking for the best option.

You switched to Blade because you use Laravel?

Seeing the code i am a little worried only about the use of JSmin, the project isn't maintened anymore and i need a stable and continued solution.

I tried to change to https://github.com/matthiasmullie/minify, but it has bugs with with JS ES6 classes.

Do you have any suggestion that can help to reach my goal?

Thanks!

**Comment by dead23angel** [comment]
hi @masimao !
I'm using Blade without using Laravel.
I also use other Laravel packages without using the framework itself, https://github.com/mattstauffer/Torch

**Comment by masimao** [comment]
Hi,

Why did you left Smarty?



Em 15/04/2017 21:52, "Ivan Gorochov" <notifications@github.com> escreveu:

hi @masimao <https://github.com/masimao> !
I'm using Blade without using Laravel.
I also use other Laravel packages without using the framework itself,
https://github.com/mattstauffer/Torch

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dead23angel/smarty-combine/issues/3#issuecomment-294326532>,
or mute the thread

**Comment by dead23angel** [comment]
Hi @masimao !
I think nothing more than a matter of taste. I did not really like Smarty from the very beginning. But the Blade came to my liking and I immediately began to use it in all my projects.

Plus, you can conveniently use .blade.php files and just .php in the first case, inside the file we will use template templates, in the second case, native php

**Comment by masimao** [comment]
Hi @dead23angel,

For now i will stay with Smarty, it fits very well in my projects. For JS minify i think i will use [Google Closure Compiler](https://michael-feichtinger.at/blog/2015/06/use-google-closure-compiler-php/), it has a nice  API, so i can take advantage of it, mainly because it is ES6 compliant.

Thanks for your tips!
